"""create leads pipelines deals

Revision ID: 26ee3c7c8b4d
Revises: 41bc0cc0c2b2
Create Date: 2026-09-26 22:10:27.969958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ee3c7c8b4d'
down_revision: Union[str, Sequence[str], None] = '41bc0cc0c2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines'))
    )
    op.create_table('pipeline_stages',
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_stages_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stages'))
    )
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('deals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deals_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_deals_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['profiles.id'], name=op.f('fk_deals_created_by_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_deals_owner_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_deals_pipeline_id_pipelines')),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], name=op.f('fk_deals_stage_id_pipeline_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_closed_at'), 'deals', ['closed_at'], unique=False)
    op.create_index(op.f('ix_deals_company_id'), 'deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_deals_contact_id'), 'deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deals_pipeline_id'), 'deals', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_deals_stage_id'), 'deals', ['stage_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_contact_id', sa.Uuid(), nullable=True),
    sa.Column('converted_company_id', sa.Uuid(), nullable=True),
    sa.Column('converted_deal_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_company_id'], ['companies.id'], name=op.f('fk_leads_converted_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_contact_id'], ['contacts.id'], name=op.f('fk_leads_converted_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_deal_id'], ['deals.id'], name=op.f('fk_leads_converted_deal_id_deals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['profiles.id'], name=op.f('fk_leads_created_by_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_leads_owner_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_stage_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_pipeline_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_contact_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_company_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_closed_at'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
